#!/bin/bash
# setup-agent-symlinks.sh
# Creates symlinks from tool-specific config files to AGENTS.md
# AGENTS.md is the single source of truth; all other files are git-ignored symlinks
#
# Covers: Claude Code (CLAUDE.md), GitHub Copilot, Cursor

set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_created() { echo -e "${GREEN}✓ Created${NC}  $1 -> $2"; }
log_skipped() { echo -e "${YELLOW}⚠ Skipped${NC}  $1 ($2)"; }
log_error()   { echo -e "${RED}✗ Error${NC}    $1: $2"; }

make_symlink() {
  local link="$1"
  local target="$2"
  local link_dir
  link_dir="$(dirname "$link")"

  mkdir -p "$link_dir"

  if [ -L "$link" ]; then
    rm "$link"
  elif [ -e "$link" ]; then
    log_skipped "$link" "real file exists, not replacing"
    return
  fi

  ln -s "$target" "$link" && log_created "$link" "$target" || log_error "$link" "symlink failed"
}

echo ""
echo "Setting up agent config symlinks..."
echo "──────────────────────────────────────"

# ── CLAUDE.md symlinks (one per AGENTS.md found in repo) ─────────────────────
echo ""
echo "Claude Code (CLAUDE.md)"

found_agents=0
while IFS= read -r agents_file; do
  found_agents=1
  dir="$(dirname "$agents_file")"
  if [ "$dir" = "." ]; then
    make_symlink "CLAUDE.md" "AGENTS.md"
  else
    make_symlink "$dir/CLAUDE.md" "AGENTS.md"
  fi
done < <(git ls-files | grep "AGENTS\.md$")

if [ "$found_agents" -eq 0 ]; then
  log_skipped "CLAUDE.md" "no AGENTS.md files tracked in git"
fi

# ── GitHub Copilot ────────────────────────────────────────────────────────────
echo ""
echo "GitHub Copilot (.github/copilot-instructions.md)"

if [ -f "AGENTS.md" ]; then
  make_symlink ".github/copilot-instructions.md" "../AGENTS.md"
else
  log_skipped ".github/copilot-instructions.md" "no root AGENTS.md found"
fi

# ── Cursor ────────────────────────────────────────────────────────────────────
echo ""
echo "Cursor (.cursor/rules/main.mdc)"

if [ -f "AGENTS.md" ]; then
  make_symlink ".cursor/rules/main.mdc" "../../AGENTS.md"
else
  log_skipped ".cursor/rules/main.mdc" "no root AGENTS.md found"
fi

# ── Ensure symlinks are gitignored ────────────────────────────────────────────
echo ""
echo "Checking .gitignore"

GITIGNORE="$REPO_ROOT/.gitignore"
IGNORE_BLOCK="# Agent config symlinks (generated by setup-agent-symlinks.sh)
**/CLAUDE.md
.github/copilot-instructions.md
.cursor/rules/main.mdc"

if [ ! -f "$GITIGNORE" ]; then
  echo "$IGNORE_BLOCK" > "$GITIGNORE"
  echo -e "${GREEN}✓ Created${NC}  .gitignore with symlink entries"
elif ! grep -q "copilot-instructions.md" "$GITIGNORE"; then
  echo "" >> "$GITIGNORE"
  echo "$IGNORE_BLOCK" >> "$GITIGNORE"
  echo -e "${GREEN}✓ Updated${NC}  .gitignore with symlink entries"
else
  echo -e "${YELLOW}⚠ Skipped${NC}  .gitignore already contains symlink entries"
fi

echo ""
echo "──────────────────────────────────────"
echo -e "${GREEN}Done.${NC}"
echo ""
